version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    groups:
      microsoft:
        applies-to: version-updates
        patterns:
          - "Microsoft.*"
          - "System.*"
        update-types:
          - minor
          - patch
      xunit:
        applies-to: version-updates
        patterns:
          - "xunit.*"
        update-types:
          - minor
          - patch
      spectre:
        applies-to: version-updates
        patterns:
          - "Spectre.*"
        update-types:
          - minor
          - patch
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily