version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      nuget-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
    groups:
      devcontainer-features:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      official-actions:
        applies-to: version-updates
        patterns:
          - "actions/*"
        update-types:
          - major
          - minor
          - patch