using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

namespace GuildWars2.Tests.Generators;

// Generates a partial AssemblyFixture with an explicit list of DTO types resolved from the referenced GW2SDK assembly.
[Generator]
internal sealed class DataTransferObjectListGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => Execute(compilation, spc));
    }

    private static void Execute(Compilation compilation, SourceProductionContext context)
    {
        IAssemblySymbol? sdk = compilation.SourceModule.ReferencedAssemblySymbols.FirstOrDefault(a => string.Equals(a.Name, "GW2SDK", StringComparison.Ordinal));
        if (sdk is null)
        {
            EmitPlaceholder(context);
            return;
        }

        List<INamedTypeSymbol> matches = [];
        Enumerate(sdk.GlobalNamespace, matches);

        if (matches.Count == 0)
        {
            EmitPlaceholder(context);
            return;
        }

        IEnumerable<INamedTypeSymbol> ordered = matches
            .OrderBy(static s => s.ContainingNamespace.ToDisplayString())
            .ThenBy(static s => s.Name);

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#pragma warning disable CS0618 // 'member' is obsolete: 'text'");
        builder.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'Type_or_Member'");
        builder.AppendLine("namespace GuildWars2.Tests.Common;");
        builder.AppendLine();
        builder.AppendLine("public partial class AssemblyFixture");
        builder.AppendLine("{");
        builder.AppendLine("    public IEnumerable<Type> DataTransferObjects { get; } = new Type[]");
        builder.AppendLine("    {");
        bool first = true;
        foreach (INamedTypeSymbol symbol in ordered)
        {
            string fqName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!first)
            {
                builder.AppendLine(",");
            }
            builder.Append("        typeof(" + fqName + ")");
            first = false;
        }
        builder.AppendLine();
        builder.AppendLine("    };");
        builder.AppendLine();
        // Collect reader types (internal static extension containers) ending with 'Json'.
        IEnumerable<INamedTypeSymbol> readers = EnumerateReaders(sdk.GlobalNamespace)
            .OrderBy(static s => s.ContainingNamespace.ToDisplayString())
            .ThenBy(static s => s.Name);
        builder.AppendLine("    public IEnumerable<System.Type> JsonElementReaderTypes { get; } = new System.Type[]");
        builder.AppendLine("    {");
        first = true;
        foreach (INamedTypeSymbol reader in readers)
        {
            string fqName = reader.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!first)
            {
                builder.AppendLine(",");
            }
            builder.Append("        typeof(" + fqName + ")");
            first = false;
        }
        builder.AppendLine();
        builder.AppendLine("    };");
        builder.AppendLine("}");

        context.AddSource("AssemblyFixture.DataTransferObjects.g.cs", builder.ToString());
    }

    private static void Enumerate(INamespaceSymbol scope, List<INamedTypeSymbol> matches)
    {
        foreach (ISymbol member in scope.GetMembers())
        {
            if (member is INamespaceSymbol ns)
            {
                Enumerate(ns, matches);
            }
            else if (member is INamedTypeSymbol type && type.TypeKind == TypeKind.Class)
            {
                foreach (AttributeData attribute in type.GetAttributes())
                {
                    if (string.Equals(attribute.AttributeClass?.Name, "DataTransferObjectAttribute", StringComparison.Ordinal))
                    {
                        // Only include types that are externally referenceable from the test assembly once InternalsVisibleTo is applied.
                        if (type.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal)
                        {
                            matches.Add(type);
                        }
                        break;
                    }
                }
            }
        }
    }

    private static void EmitPlaceholder(SourceProductionContext context)
    {
        context.AddSource("AssemblyFixture.DataTransferObjects.g.cs",
            """
            // <auto-generated/>
            namespace GuildWars2.Tests.Common;
            public partial class AssemblyFixture
            {
                public IEnumerable<System.Type> DataTransferObjects { get; } = new System.Type[] { };
                public IEnumerable<System.Type> JsonElementReaderTypes { get; } = new System.Type[] { };
            }
            """);
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateReaders(INamespaceSymbol scope)
    {
        foreach (ISymbol member in scope.GetMembers())
        {
            if (member is INamespaceSymbol ns)
            {
                foreach (INamedTypeSymbol nested in EnumerateReaders(ns))
                {
                    yield return nested;
                }
            }
            else if (member is INamedTypeSymbol type && type.TypeKind == TypeKind.Class)
            {
                if (type.Name.EndsWith("Json", StringComparison.Ordinal)
                    && type.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal)
                {
                    yield return type;
                }
            }
        }
    }
}
