using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

namespace GuildWars2.Tests.Generators;

// Generates a partial AssemblyFixture with an explicit list of exported enum types resolved from the referenced GW2SDK assembly.
[Generator]
internal sealed class EnumListGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => Execute(compilation, spc));
    }

    private static void Execute(Compilation compilation, SourceProductionContext context)
    {
        IAssemblySymbol? sdk = compilation.SourceModule.ReferencedAssemblySymbols.FirstOrDefault(a => string.Equals(a.Name, "GW2SDK", StringComparison.Ordinal));
        if (sdk is null)
        {
            EmitPlaceholder(context);
            return;
        }

        List<INamedTypeSymbol> enums = [];
        Enumerate(sdk.GlobalNamespace, enums);

        if (enums.Count == 0)
        {
            EmitPlaceholder(context);
            return;
        }

        IEnumerable<INamedTypeSymbol> ordered = enums
            .OrderBy(static s => s.ContainingNamespace.ToDisplayString())
            .ThenBy(static s => s.Name);

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#pragma warning disable CS0618 // 'member' is obsolete: 'text'");
        builder.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'Type_or_Member'");
        builder.AppendLine("namespace GuildWars2.Tests.Common;");
        builder.AppendLine();
        builder.AppendLine("public partial class AssemblyFixture");
        builder.AppendLine("{");
        builder.AppendLine("    public System.Type[] ExportedEnums { get; } = new System.Type[]");
        builder.AppendLine("    {");
        bool first = true;
        foreach (INamedTypeSymbol symbol in ordered)
        {
            string fqName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!first)
            {
                builder.AppendLine(",");
            }
            builder.Append("        typeof(" + fqName + ")");
            first = false;
        }
        builder.AppendLine();
        builder.AppendLine("    }; ");
        builder.AppendLine("}");
        builder.AppendLine("#pragma warning restore CS0618");

        context.AddSource("AssemblyFixture.Enums.g.cs", builder.ToString());
    }

    private static void Enumerate(INamespaceSymbol scope, List<INamedTypeSymbol> enums)
    {
        foreach (ISymbol member in scope.GetMembers())
        {
            if (member is INamespaceSymbol ns)
            {
                Enumerate(ns, enums);
            }
            else if (member is INamedTypeSymbol type && type.TypeKind == TypeKind.Enum)
            {
                if (type.DeclaredAccessibility == Accessibility.Public)
                {
                    enums.Add(type);
                }
            }
        }
    }

    private static void EmitPlaceholder(SourceProductionContext context)
    {
        context.AddSource("AssemblyFixture.Enums.g.cs", """
            // <auto-generated/>
            namespace GuildWars2.Tests.Common;
            public partial class AssemblyFixture
            {
                public System.Type[] ExportedEnums { get; } = new System.Type[] { };
            }
            """); // Placeholder when no enums found
    }
}
