// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

using GuildWars2.Hero.Accounts;

namespace GuildWars2;

#if NET
/// <summary>
/// Provides source-generated JSON serialization metadata for Guild Wars 2 types.
/// </summary>
[JsonSerializable(typeof(global::GuildWars2.Coin))]
[JsonSerializable(typeof(global::GuildWars2.Items.Item))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Crafting.Disciplines.LearnedCraftingDisciplines))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Crafting.Recipes.Recipe))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.MailCarriers.MailCarrier))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.JadeBots.JadeBotSkin))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Gliders.GliderSkin))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Outfits.Outfit))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Skiffs.SkiffSkin))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Finishers.Finisher))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Finishers.UnlockedFinisher))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Mounts.Mount))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Templates.BoundLegendaryItem))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Mounts.MountSkin))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Wardrobe.EquipmentSkin))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Dyes.DyeColor))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Templates.CharacterEquipment))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Templates.EquipmentTemplate))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Templates.LegendaryItem))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Miniatures.Miniature))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Equipment.Novelties.Novelty))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Achievements.Groups.AchievementGroup))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Achievements.Titles.Title))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Achievements.Categories.AchievementCategory))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Achievements.Achievement))]
[JsonSerializable(typeof(global::GuildWars2.Hero.Achievements.AccountAchievement))]
public sealed partial class GuildWars2JsonContext : JsonSerializerContext;
#endif
