using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

namespace GuildWars2.Tests.Generators;

// Generates a partial AssemblyFixture with explicit lists supporting DesignedForInheritanceTest
[Generator]
internal sealed class InheritanceDesignGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => Execute(compilation, spc));
    }

    private static void Execute(Compilation compilation, SourceProductionContext context)
    {
        IAssemblySymbol? sdk = compilation.SourceModule.ReferencedAssemblySymbols.FirstOrDefault(a => string.Equals(a.Name, "GW2SDK", StringComparison.Ordinal));
        if (sdk is null)
        {
            EmitPlaceholder(context);
            return;
        }

        List<INamedTypeSymbol> exportedClasses = [];
        List<INamedTypeSymbol> inheritableClasses = [];
        Enumerate(sdk.GlobalNamespace, exportedClasses, inheritableClasses);

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#pragma warning disable CS0618");
        builder.AppendLine("namespace GuildWars2.Tests.TestInfrastructure;");
        builder.AppendLine();
        builder.AppendLine("public partial class AssemblyFixture");
        builder.AppendLine("{");

        // Exported classes
        builder.AppendLine("    public System.Type[] ExportedClasses { get; } = new System.Type[]");
        builder.AppendLine("    {");
        bool first = true;
        foreach (INamedTypeSymbol type in exportedClasses
            .OrderBy(static t => t.ContainingNamespace.ToDisplayString())
            .ThenBy(static t => t.Name))
        {
            if (!first)
            {
                builder.AppendLine(",");
            }
            builder.Append("        typeof(" + FormatType(type) + ")");
            first = false;
        }
        builder.AppendLine();
        builder.AppendLine("    };\n");

        // Inheritable classes
        builder.AppendLine("    public System.Type[] InheritableClasses { get; } = new System.Type[]");
        builder.AppendLine("    {");
        first = true;
        foreach (INamedTypeSymbol type in inheritableClasses
            .OrderBy(static t => t.ContainingNamespace.ToDisplayString())
            .ThenBy(static t => t.Name))
        {
            if (!first)
            {
                builder.AppendLine(",");
            }
            builder.Append("        typeof(" + FormatType(type) + ")");
            first = false;
        }
        builder.AppendLine();
        builder.AppendLine("    };\n");

        builder.AppendLine("}");
        builder.AppendLine("#pragma warning restore CS0618");
        context.AddSource("AssemblyFixture.Inheritance.g.cs", builder.ToString());
    }

    private static void Enumerate(INamespaceSymbol scope, List<INamedTypeSymbol> exportedClasses, List<INamedTypeSymbol> inheritableClasses)
    {
        foreach (ISymbol member in scope.GetMembers())
        {
            if (member is INamespaceSymbol ns)
            {
                Enumerate(ns, exportedClasses, inheritableClasses);
            }
            else if (member is INamedTypeSymbol type && type.TypeKind == TypeKind.Class)
            {
                if (type.DeclaredAccessibility == Accessibility.Public && !IsObsoleteError(type))
                {
                    exportedClasses.Add(type);
                    if (HasInheritableAttribute(type))
                    {
                        inheritableClasses.Add(type);
                    }
                }
            }
        }
    }

    private static bool IsObsoleteError(INamedTypeSymbol type)
    {
        foreach (AttributeData attribute in type.GetAttributes())
        {
            if (string.Equals(attribute.AttributeClass?.Name, "ObsoleteAttribute", StringComparison.Ordinal))
            {
                if (attribute.ConstructorArguments.Length == 2)
                {
                    // (string message, bool error)
                    if (attribute.ConstructorArguments[1].Value is bool isError && isError)
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    private static string FormatType(INamedTypeSymbol type)
    {
        // Build a fully qualified name without generic parameter identifiers, using arity commas.
        Stack<string> parts = new();
        INamedTypeSymbol? current = type;
        while (current is not null)
        {
            string name = current.Name;
            int arity = current.TypeParameters.Length;
            if (arity > 0)
            {
                name += "<" + new string(',', arity - 1) + ">"; // e.g. <,> for arity 2
            }

            parts.Push(name);
            current = current.ContainingType;
        }

        string ns = type.ContainingNamespace.IsGlobalNamespace
            ? "global::"
            : "global::" + type.ContainingNamespace.ToDisplayString() + ".";

        return ns + string.Join(".", parts);
    }

    private static bool HasInheritableAttribute(INamedTypeSymbol type)
    {
        foreach (AttributeData attribute in type.GetAttributes())
        {
            if (string.Equals(attribute.AttributeClass?.Name, "InheritableAttribute", StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static void EmitPlaceholder(SourceProductionContext context)
    {
        context.AddSource("AssemblyFixture.Inheritance.g.cs", "// <auto-generated/>\nnamespace GuildWars2.Tests.TestInfrastructure;\npublic partial class AssemblyFixture { public System.Type[] ExportedClasses { get; } = new System.Type[] { }; public System.Type[] InheritableClasses { get; } = new System.Type[] { }; }");
    }
}
