# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build a dev container image
on: 
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '30 17 * * 0'
  push:
    branches:
    - main
    - feature/publish-devcontainer
    paths:
    - .devcontainer/**

jobs:
  build-and-push:
    name: Build and push dev container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - run: npm install -g @vscode/dev-container-cli
    - run: devcontainer build --image-name ghcr.io/StevenLiekens/gw2sdk/devcontainer
    - run: docker push ghcr.io/StevenLiekens/gw2sdk/devcontainer:latest
        
