name: Build a dev container image
on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "30 17 * * 0"
  push:
    branches:
      - main
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer.yml

jobs:
  build-and-push:
    name: Build and push dev container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Build and push ghcr.io/sliekens/gw2sdk/devcontainer
        run: devcontainer build --no-cache --image-name ghcr.io/sliekens/gw2sdk/devcontainer --push --workspace-folder . --config .devcontainer/devcontainer-build.json
