name: Update GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
    - docs/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Publish docs to gh-pages
        run: ./publish.sh
        if:  ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}