name: Release

on:
  workflow_dispatch:
  push:
    tags: v*

env:
  SYMBOL_PACKAGE: true

jobs:
  build:
    name: Build
    env:
      build-configuration: Release
    runs-on: ubuntu-latest
    container: ghcr.io/sliekens/gw2sdk/devcontainer:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # (no history limit)
          filter: tree:0

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --configuration ${{ env.build-configuration }} --no-restore

      - name: Pack artifacts
        run: dotnet pack GW2SDK --configuration ${{ env.build-configuration }} --no-build --output artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: artifacts

  deploy-to-github-packages:
    name: Deploy to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-packages
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: artifacts

      - name: Upload packages to GitHub Packages
        run: dotnet nuget push artifacts/*.nupkg --source https://nuget.pkg.github.com/sliekens/index.json --api-key ${{secrets.GITHUB_TOKEN}}
