name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  SYMBOL_PACKAGE: true
  DOTNET_TEST_TFM: net9.0

jobs:
  build:
    name: Build
    env:
      build-configuration: Release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sliekens/gw2sdk/devcontainer:latest
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # (no history limit)
          filter: tree:0

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --configuration ${{ env.build-configuration }} --no-restore
        
      - name: Test
        run: dotnet exec GW2SDK.Tests/bin/${{ env.build-configuration }}/$DOTNET_TEST_TFM/GW2SDK.Tests.dll --coverage --coverage-settings GW2SDK.Tests/coverage.settings --coverage-output coverage.xml
        env:
          ApiKeyBasic: ${{ secrets.API_TOKEN_BASIC }}
          ApiKey: ${{ secrets.API_TOKEN_FULL }}
          GuildLeader__Token: ${{ secrets.API_TOKEN_GUILD_LEADER }}

      - name: Create packages
        run: dotnet pack GW2SDK --configuration ${{ env.build-configuration }} --no-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/package/${{ env.build-configuration }}

  deploy-integration:
    name: Deploy to NuGet integration environment
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: nuget-integration
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: artifacts

      - name: Push packages
        run: dotnet nuget push artifacts/*.nupkg --source ${{ vars.NUGET_API_URL }} --api-key ${{ secrets.NUGET_API_KEY }}

  deploy:
    name: Deploy to NuGet
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: nuget
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: artifacts

      - name: Push packages
        run: dotnet nuget push artifacts/*.nupkg --source ${{ vars.NUGET_API_URL }} --api-key ${{ secrets.NUGET_API_KEY }}
