name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  SYMBOL_PACKAGE: true

jobs:
  build:
    name: Build
    env:
      build-configuration: Release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sliekens/gw2sdk/devcontainer:latest
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # (no history limit)
          filter: tree:0

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --configuration ${{ env.build-configuration }} --no-restore

      - name: Create packages
        run: dotnet pack GW2SDK --configuration ${{ env.build-configuration }} --no-build --output artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: artifacts

  deploy-integration:
    name: Deploy to NuGet integration environment
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: nuget-integration
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: artifacts

      - name: Push packages
        run: dotnet nuget push artifacts/*.nupkg --source ${{ vars.NUGET_API_URL }} --api-key ${{ secrets.NUGET_API_KEY }}

  deploy:
    name: Deploy to NuGet
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: nuget
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: artifacts

      - name: Push packages
        run: dotnet nuget push artifacts/*.nupkg --source ${{ vars.NUGET_API_URL }} --api-key ${{ secrets.NUGET_API_KEY }}